name: dahdit-test
version: 0.5.0

github: ejconlon/dahdit-test
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: Test utils for Dahdit serde
description: Please see the README on GitHub at <https://github.com/ejconlon/dahdit-test#readme>
tested-with: GHC == 9.2.7

language: GHC2021

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- bytestring >= 0.11 && < 0.12
- containers >= 0.6 && < 0.7
- dahdit >= 0.5 && < 0.6
- daytripper >= 0.3 && < 0.4
- directory >= 1.3 && < 1.4
- falsify >= 0.2 && < 0.3
- text >= 1.2 && < 2.1

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  dahdit-test-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dahdit-test
    - tasty >= 1.4 && < 1.5
