resolver: lts-23.0

ghc-options:
  "$everything": -haddock

packages:
- dahdit
- dahdit-test
- dahdit-network
- dahdit-midi

extra-deps:
- data-sword-0.2.0.3
- daytripper-1.0.0
- prop-unit-1.0.1
- nanotime-0.3.2

