resolver: lts-22.7

ghc-options:
  "$everything": -haddock

packages:
- dahdit
- dahdit-test
- dahdit-network
- dahdit-midi

extra-deps:
- data-sword-0.2.0.3
- daytripper-0.3.1
- falsify-0.2.0
- nanotime-0.1.0

allow-newer: true
allow-newer-deps:
- falsify

