resolver: lts-23.18

ghc-options:
  "$everything": -haddock

packages:
- dahdit
- dahdit-test
- dahdit-network
- dahdit-midi
- dahdit-audio

extra-deps:
- aeson-via-0.2.3
- data-sword-0.2.0.3
- daytripper-1.0.0
- prop-unit-1.0.1
- nanotime-0.3.2

