resolver: lts-21.6

ghc-options:
  "$everything": -haddock

packages:
- dahdit
- dahdit-test
- dahdit-network

extra-deps:
- data-sword-0.2.0.3
- daytripper-0.2.0
# TODO Use Hackage release with GenDefault
# - falsify-0.2.0
- git: git@github.com:well-typed/falsify.git
  commit: 51fc95d907ffe008f27a8c450dbf41854668e07d
  subdirs:
  - lib
