name: dahdit-midi
version: 0.5.3

github: ejconlon/dahdit
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: MIDI and OSC parsing/printing with dahdit
description: Please see the README on GitHub at <https://github.com/ejconlon/dahdit#readme>
tested-with: GHC == 9.2.7

language: GHC2021

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- dahdit >= 0.5 && < 0.6
- bytestring >= 0.11 && < 0.12
- containers >= 0.6 && < 0.7
- data-sword >= 0.2.0.3 && < 0.3
- hashable >= 1.4 && < 1.5
- nanotime >= 0.3 && < 0.4
- newtype >= 0.2 && < 0.3
- primitive >= 0.7 && < 0.9
- text >= 1.2 && < 2.1
- vector >= 0.12 && < 0.14

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  dahdit-midi-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dahdit-midi
    - dahdit-test
    - daytripper
    - falsify
    - tasty
    - directory
    - filepath
