name: dahdit-audio
version: 0.7.0

github: ejconlon/dahdit
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2023 Eric Conlon
synopsis: Audio file parsing/printing with dahdit
description: Please see the README on GitHub at <https://github.com/ejconlon/dahdit#readme>
tested-with: GHC == 9.8.4

language: GHC2021

extra-source-files:
- README.md

dependencies:
- base >= 4.12 && < 5
- bytestring >= 0.12 && < 0.13
- containers >= 0.6 && < 0.7
- dahdit >= 0.7 && < 0.8
- data-default >= 0.7 && < 0.8
- data-sword >= 0.2 && < 0.3
- digest >= 0.0.1 && < 0.0.3
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.5
- mtl >= 2.2 && < 2.4
- primitive >= 0.9 && < 0.10
- regex-tdfa >= 1.3 && < 1.4
- text >= 2.1 && < 2.2
- transformers >= 0.5 && < 0.7
- microlens >= 0.4 && < 0.5
- prettyprinter >= 1.7 && < 1.8
- aeson >= 2.2 && < 2.3
- aeson-via >= 0.2 && < 0.3
- aeson-pretty >= 0.8 && < 0.9
- optparse-applicative >= 0.16 && < 0.19
- aeson-casing >= 0.2 && < 0.3
- pathwalk >= 0.3 && < 0.4
# Used as build plugin
- ghc-typelits-knownnat >= 0.7 && < 0.8

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  dahdit-audio-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dahdit-audio
    - tasty >= 1.5 && < 1.6
    - tasty-hunit >= 0.10 && < 0.11
    - daytripper
