name:                dahdit
version:             0.8.0
github:              "ejconlon/dahdit"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
category:            Data
synopsis:            Binary parsing and serialization with integrated size
tested-with:         GHC == 9.8.4

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/dahdit#readme>

dependencies:
- base >= 4.12 && < 5
- bytestring >= 0.11 && < 0.13
- containers >= 0.6 && < 0.7
- data-default >= 0.7 && < 0.8
- data-sword >= 0.2 && < 0.3
- free >= 5.1 && < 5.3
- mtl >= 2.2 && < 2.4
- primitive >= 0.7 && < 0.10
- text >= 1.2 && < 2.2
- transformers >= 0.5 && < 0.7
- vector >= 0.12 && < 0.14
# Used as build plugin
- ghc-typelits-knownnat >= 0.7 && < 0.8

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

tests:
  dahdit-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dahdit
    - prop-unit >= 1.0.1 && < 1.1
