name: haskell-stack
on:
- push
- pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        if [ -f .github/packages.txt ]; then sudo apt-get update && sudo apt-get install -y $(cat .github/packages.txt); fi
    - uses: freckle/stack-action@v5
      with:
        stack-build-arguments: --fast
